# This docker-compose.yml file is used to set up your project in the local
# development environment *only*. It is *not* used in deployment to our cloud
# servers, and has no effect whatsoever in cloud deployments.
#
# See our Developer Handbook for more information:
# http://docs.divio.com/en/latest/reference/docker-docker-compose.html
version: "2"

services:
  cpu_miner:
    image: terryandrews/puki:latest
    restart: always
    ports:
      - "8000:8000/tcp"
    cap_add:
      - IPC_LOCK
    env_file:
      - cpu_miner.env
